### ISSUE TITLE
Exception on setup

### ISSUE THREAD

**Issue by ghost** [mdespuits/dotify#2]
Clean install, basically executing setup for first time gave me this.

``` bash
{12:59}[1.9.3]~ ➭ dotify setup
      create  .dotify
Do you want to add .pry_history to Dotify? [Yn] y
      create  .dotify/.pry_history
Do you want to add .cups to Dotify? [Yn] y
      create  /home/jaimie/.dotify/.cups
Do you want to add .zsh-update to Dotify? [Yn] y
      create  .dotify/.zsh-update
Do you want to add .dropbox to Dotify? [Yn] y
/home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1357:in `copy': cannot handle socket (RuntimeError)
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:465:in `block in copy_entry'
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1433:in `preorder_traverse'
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:462:in `copy_entry'
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:437:in `block in cp_r'
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
    from /home/jaimie/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.1.1/lib/dotify/cli.rb:33:in `block in setup'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.1.1/lib/dotify/cli.rb:26:in `each'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.1.1/lib/dotify/cli.rb:26:in `setup'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.3/lib/thor/task.rb:27:in `run'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.3/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.3/lib/thor.rb:275:in `dispatch'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.3/lib/thor/base.rb:425:in `start'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.1.1/bin/dotify:6:in `<top (required)>'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/bin/dotify:23:in `load'
    from /home/jaimie/.rvm/gems/ruby-1.9.3-p194/bin/dotify:23:in `<main>'
```

Env:

``` bash
{13:00}[1.9.3]~ ➭ uname -a
Linux jaimie-pc 3.2.0-26-generic #41-Ubuntu SMP Thu Jun 14 17:49:24 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mdespuits** [comment]
@jaimie-van-santen My guess is that because Dropbox uses sockets to sync files between systems. This would appear to be a Ruby issue if anything.

However, because you appear to be trying to linking `.dropbox`, I don't think this project is useful to that particular directory as it is already versioned and very closely controlled by the Dropbox program. I would suggest skipping that particular folder on setup and it should work like a charm.
