### ISSUE TITLE
symbolize_keys!': undefined method `each' for false:FalseClass (NoMethodError)

### ISSUE THREAD

**Issue by alexkalish** [mdespuits/dotify#5]
1. This sounds awesome!  I've been looking for exactly this kind of utility.
2. I had to manually install thor, git and multi_json.  I think they should go into the gemspec as dependencies?
3. Whenever I try to `dotify install` I get the following error:

``` bash
(ruby-1.9.3) ~ $ dotify install
/Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/config.rb:65:in `symbolize_keys!': undefined method `each' for false:FalseClass (NoMethodError)
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/config.rb:48:in `retrieve'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/config.rb:43:in `ignore'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/filter.rb:26:in `filter_ignore_files!'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/filter.rb:9:in `home'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/collection.rb:11:in `initialize'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify.rb:23:in `new'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify.rb:23:in `collection'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/cli.rb:160:in `link'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/invocation.rb:109:in `invoke'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/lib/dotify/cli.rb:142:in `install'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/gems/dotify-0.6.3/bin/dotify:6:in `<top (required)>'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/bin/dotify:19:in `load'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/bin/dotify:19:in `<main>'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/alexkalish/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

Any ideas?

Thanks.

**Comment by mdespuits** [comment]
1. [Currently moving dependencies](https://github.com/mattdbridges/dotify/commit/808fee2b49dadb1a2a1397a29ed2f3a032f92670) back into `dotify.gemspec` file and will release a patch level version.
2. I'll see if I can reproduce the error on my own system from a fresh install. I'll follow up once I have a little more info.

**Comment by mdespuits** [comment]
Just released [v0.6.4](https://github.com/mattdbridges/dotify/tree/v0.6.4) with a few other bug fixes and updates to the codebase. You should be able to install this version without installing other gems manually. I will follow up on the other issue within the next day or so.

**Comment by shanesveller** [comment]
I am also seeing this on a fresh install of v0.6.4 with 1.9.3p194 via rbenv+ruby-build from homebrew, for when you are reviewing the `dotify install` issue:

``` bash
shane@Freyja ~/ruby> dotify install
      create  /Users/shane/.dotify
      create  /Users/shane/.dotrc
Editing config file...
'.dotrc' has not been linked by Dotify. Please run `dotify link .dotrc` to edit this file.
Config file updated.
/usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/config.rb:65:in `symbolize_keys!': undefined method `each' for false:FalseClass (NoMethodError)
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/config.rb:48:in `retrieve'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/config.rb:43:in `ignore'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/filter.rb:26:in `filter_ignore_files!'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/filter.rb:9:in `home'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/collection.rb:11:in `initialize'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify.rb:23:in `new'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify.rb:23:in `collection'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/cli.rb:156:in `link'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor/invocation.rb:109:in `invoke'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/lib/dotify/cli.rb:138:in `install'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dotify-0.6.4/bin/dotify:6:in `<top (required)>'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/bin/dotify:23:in `load'
    from /usr/local/Cellar/rbenv/0.3.0/versions/1.9.3-p194/bin/dotify:23:in `<main>'
shane@Freyja ~/ruby>
```

**Comment by mdespuits** [comment]
This should resolve the issue. I replicated it on my installation and found the issue. Please install the latest version and let me know how it works. I will close the issue if you are no longer having problems.

**Comment by mdespuits** [comment]
@shanesveller @alexkalish Are you still having issues with the latest release (0.6.5)? If not, I will close this issue.

**Comment by shanesveller** [comment]
I will test it when I get home this evening, thanks!

**Comment by alexkalish** [comment]
Thanks for the quick response!  I did try this yesterday and can confirm it fixed all of my issues.

**Comment by mdespuits** [comment]
@shanesveller Can you confirm that it works. I will close this issue after your confirmation.

**Comment by shanesveller** [comment]
Yep, all good here, thanks for addressing and sorry for the delay in
responding!

**Comment by mdespuits** [comment]
Thanks! Glad you have a working version..
